# Configuration file for [`cargo-release`](https://github.com/crate-ci/cargo-release)
# See: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

allow-branch = ["master"]
sign-commit = true
sign-tag = true
shared-version = true
pre-release-commit-message = "chore: release {{version}}"
tag-prefix = "" # tag only once instead of per every crate
